version: "3.3"
services:
  application1:
    build: ./application/
    ports:
      - "8081:8080"
  application2:
    build: ./application/
    ports:
      - "8082:8080"
  prometheus:
    image: prom/prometheus
    ports:
      - "9091:9090"
    volumes:
      - type: bind 
        source: ./prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana-enterprise
    restart: unless-stopped
    ports:
     - '3000:3000'
    #volumes:
    #  - grafana-storage:/var/lib/grafana
  node-exporter-config:
    image: alpine
    volumes:
      - textfile_collector:/textfile_collector
    command: sh -c 'echo -e "machine_role{role=\"postfix\"} 1\nmachine_role{role=\"apache\"} 1" > textfile_collector/roles.prom'
  node_exporter:
    depends_on: [node-exporter-config]
    image: prom/node-exporter
    command: ["--collector.textfile.directory", "textfile_collector"]
    ports:
      - "9100:9100"
    volumes:
      - textfile_collector:/textfile_collector
volumes:
  textfile_collector: {}
  #grafana-storage: {}